# Generated by Django 4.1 on 2022-08-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuarters', '0004_pemohon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemohon',
            name='tarikh_mula_bekerja',
        ),
    ]
