# Generated by Django 4.1 on 2022-08-05 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kuarters', '0003_pemohon_tinggal_bersama'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemohon',
            name='status',
            field=models.CharField(choices=[('b', 'bujang'), ('k', 'berkahwin')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
